[build]
beforeBuildCommand = "pnpm run build"
beforeDevCommand = "pnpm run dev"
devPath = "http://localhost:1420"
distDir = "./dist"

[package]
productName = "Vista App"

[tauri]

[tauri.allowlist]
shell = { open = "^(https?://\\w+).+" }
os.all = true

[tauri.security]
# csp =

# [tauri.updater]
# active = true
# endpoints = ["https://vrc-get.anatawa12.com/api/gui/tauri-updater.json"]
# dialog = true
# pubkey = "dW50cnVzdGVkIGNvbW1lbnQ6IG1pbmlzaWduIHB1YmxpYyBrZXk6IDkyMjAzMkU2Q0ZGQjQ0MjYKUldRbVJQdlA1aklna2d2NnRoM3ZsT3lzWEQ3MC9zTGpaWVR4NGdQOXR0UGJaOHBlY2xCcFY5bHcK"

[tauri.bundle]
active = true
targets = [
    # "appimage",
    # "nsis",     #-setup.exe
    "app",      # needs for dmg
    "dmg",

    # "updater", # auto update
]
longDescription = "Vista is another vrc-get GUI"
shortDescription = "Vista - Another vrc-get GUI"
identifier = "dev.aika.vista-app"
category = "DeveloperTool"
copyright = "(c) gizmo and anatawa12 and other contributors"

externalBin = []
icon = [
    "icons/32x32.png",
    "icons/128x128.png",
    "icons/128x128@2x.png",
    "icons/icon.icns",
    "icons/icon.ico",
]
resources = []

[tauri.bundle.deb]
depends = []

[tauri.bundle.macOS]
exceptionDomain = ""
frameworks = []
providerShortName = "gizmo"

[tauri.bundle.windows]
digestAlgorithm = "sha256"
